# Generated by Django 5.0.2 on 2024-03-23 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_title', models.CharField(max_length=255)),
                ('charge_percentage', models.DecimalField(decimal_places=2, default=1, max_digits=100000)),
                ('charge_fixed_rate', models.DecimalField(decimal_places=2, default=1, max_digits=100000)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed Rate'), ('percentage', 'Percentage')], default='fixed', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode_name', models.CharField(max_length=255)),
                ('payment_mode_type_string', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bil_type', models.CharField(max_length=255)),
                ('bil_description', models.TextField()),
                ('bil_number', models.CharField(max_length=255)),
                ('bil_receipt_date', models.DateField()),
                ('bil_items', models.TextField()),
                ('bil_total_with_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bil_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Rate')], default='percentage', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bills')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.charges')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='bil_charges',
            field=models.ManyToManyField(through='bills.BillCharge', to='bills.charges'),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bills')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.item')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=255)),
                ('receipt_description', models.TextField()),
                ('receipt_number', models.IntegerField()),
                ('receipt_date', models.DateField()),
                ('receipt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Rate')], default='percentage', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.charges')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.receipt')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_charges',
            field=models.ManyToManyField(through='bills.ReceiptCharge', to='bills.charges'),
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.receipt')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_items',
            field=models.ManyToManyField(through='bills.ReceiptItem', to='bills.item'),
        ),
    ]
