# Generated by Django 5.0.2 on 2024-02-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_title', models.CharField(max_length=255)),
                ('charge_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('charge_fixed_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode_name', models.CharField(max_length=255)),
                ('payment_mode_type_string', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=255)),
                ('receipt_description', models.TextField()),
                ('receipt_number', models.IntegerField()),
                ('receipt_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=255)),
                ('role_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bil_type', models.CharField(max_length=255)),
                ('bil_description', models.TextField()),
                ('bil_number', models.CharField(max_length=255)),
                ('bil_receipt_date', models.DateField()),
                ('bil_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Rate')], default='percentage', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bills')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.charges')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='bil_charges',
            field=models.ManyToManyField(through='bills.BillCharge', to='bills.charges'),
        ),
        migrations.CreateModel(
            name='ReceiptCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Rate')], default='percentage', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.charges')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.receipt')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_charges',
            field=models.ManyToManyField(through='bills.ReceiptCharge', to='bills.charges'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_dob', models.DateField()),
                ('user_address', models.TextField()),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.role')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.user'),
        ),
    ]
