# Generated by Django 5.0.2 on 2024-03-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bills_bil_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bil_total_with_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
