# Generated by Django 5.0.2 on 2024-03-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bills_bil_total_with_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='charge_type',
            field=models.CharField(choices=[('fixed', 'Fixed Rate'), ('percentage', 'Percentage')], default='fixed', max_length=10),
        ),
    ]
